### ISSUE TITLE
Issue with hire additional assets while assets are still avalieble

### ISSUE THREAD

**Issue by dlebedynskyi** [noonereally/NW-Profession-Bot#16]
Hi, 
I saw today that for Mailsmith and Alchemy ( may be more) script was hiring additional workers. While purple ones where still avalieble.  As for mailsmith - had 2 purples and 2 slots set. Script was executing hire additional in those 2 slots instead of level task. 
This is different from what it was before when we had hire only if no work assets left. 
Smart Asset allocation for leadership and Fill Optional Assets are ON. 

Both professions are lvl 20+. Will be looks for more details. Im using your latest script. 

Example for alchemy lvl 21.  As you can see Assistant Alchemist is available.  we should not be hiring new assets
![image](https://cloud.githubusercontent.com/assets/1182917/7090408/f9dd18fc-df70-11e4-9f87-7fd2039ec9c9.png)

**Comment by noonereally** [comment]
I've noticed the same, but when i tried to do it manually i noticed the gateway doesn't recognize the main worker, and wont let the task start until i swap them out and back in or reload the gateway, so I thought it was the problem.
I don't really see any thing changed in the code that can do that.
All i can think if trying is putting some console.logs at SelectItemFor function to find something, and maybe comment out the leadership block. I don't have better ideas.

**Comment by dlebedynskyi** [comment]
Yeah might be worth trying. I have not looked at leadership changes implemented. but this periodically reproduces on various professions

**Comment by dlebedynskyi** [comment]
Ok I think i see what the issue possible is about. @Phr33d0m you might want to read this too since I think it is in main brunch too. 

Before for worker we used logic - assign workers from low to top. So
Now we have from top to low. _This is wrong_.

This leads to a point that we start to hire missing workers even thought we have 4 major assets and 4 slots. We pile up all 4 in one slot. Then on next task  we already don't have high level workers. so we pick highest available or hire new ones. Then we have high first task end  and some other one is slotted instead. We end up having 3 major assets standing. 

Mind this - for tools from high to low is correct way and should not change ( as it was before).

**Comment by noonereally** [comment]
Hmmm I think it was always top to low, and i never changed it.
I don't see how it makes the higher become idle, the higher are slotted to fill the purples first and new not made unless they all were piled up and there is none to make the task, and that is not optimal but how it worked.

yes it will make unnecessary higher rank commons instead of spreading the higher ranks, but in no case the high ranks should be idle in high to low assignment.
And this can be fixed with @WloBeb idea for leadership but expanded to all professions.

That alchemist shouldn't be idle, he was supposed to be selected for the second slot.
If slotted low to high, in case of many commons and few purples, all the purples will remain idle as all the +5% slots will be filled but none of the +50% will be used.

I just noticed something, that makes me believe it is a gateway error and not script, the first slot is automatically assigned to highest by the gateway, the function assigns the optionals and not the first one. So that alchemist should have gone into the main/mandatory slot

**Comment by WloBeb** [comment]
Let's look closer at above situation with Alchemy.
In slot 2 we have "Hire additional Apothecary" from ~10h
In slot 3 we have "Hire additional Apothecary" from ~6 min
In slot 1 we have "Gather advanced components" from ~1-2min

If previous task in slot 1 used more than one worker eg it was "Alchemical Reserch" everything is corect: 6 min before it wasn't free worker so "Hire ..." starts. Then task in slot 1 has been completed and relesed 2 workers, of which only 1 was used to new task.

**Comment by noonereally** [comment]
hehe, I guess it can be closed now, thanks WloBeb.

**Comment by Phr33d0m** [comment]
On a side note: @noonereally you now have direct write access to the main repo. Keep up the good work :-)

**Comment by dlebedynskyi** [comment]
@WloBeb  you are correct. But defect  still is actual. 
Just run in the same situation  with Mail smith - and I have like 6 available purple assets .
And yes 

```
in SelectItemFor
 var quality = [".Special", ".Gold", ".Silver", ".Bronze"];
....
 // if no asset was selected, check for persons for best speed, in descending order
            if (!clicked) {
                for (ic in quality) {
                    $it = $persons.filter(quality[ic]);

```

so we do go from top to low still. Same as tools. Not sure that reverse will help. Issue seems to be deeper then this reverse.

**Comment by dlebedynskyi** [comment]
Also - we hire new workers. But we never call them to upgrade.

**Comment by WloBeb** [comment]
@dlebedynskyi for me it isn't defect, but the appropriate and desirable order.
