### ISSUE TITLE
Shorter profiles

### ISSUE THREAD

**Issue by noonereally** [noonereally/NW-Profession-Bot#19]
@dlebedynskyi, @WloBeb
I've added a loop to check lower level task lists if the current level is null (false in if),
So gathering profiles can be made of 4 lines, for example
`profile: {
level : {
     1 : [basic..]
      6 : [not basic]
`
at 5 it should loop back to 1
and at 8 to 6  for example.

But i noticed that most of the profiles are added via the function and not directly,
but merging a profile like that with default no be correct. 
So I suggest we refactor the AddTodefine to have the profile name as a mandatory second parameter and accept null.
So on null it will add a totally new profile to the profession.

**Comment by dlebedynskyi** [comment]
I was thinking on something like this but that one was quicker and less freaking debugging in monkey. 
After some thinking 
have base line for level  
1 : [base] 
then 2 -5 will use same line. 
2 : 1, 
3: 2 ...
6: [specific] 
And then 7+ will use 6 as base until override. 
7 :  6 
8:  7 
9 : 8 ...
Thing is that we usually have iterative profile lines. So having 7 using base same as in 1 would not make any sense to me. Instead having 7,8,9 using previous one as base if not defined may work better. What do you think ? 
I do still like the idea of having basic profile to override as parameter. But passing null to create a new profile without override sounds good to me too.

**Comment by Phr33d0m** [comment]
@noonereally's approach uses (a bit) less memory (yes, on small systems this **does** matter), so I like it.

**Comment by dlebedynskyi** [comment]
can be closed I Think since function is merged with recursive lists. we might also develop this further but we might need to change both sides -how we setup profiles and how we check them. Also with possible changes to indexDB we might not have to worry about memory so much since data won't be stored in memory. Just a thought

**Comment by WloBeb** [comment]
@dlebedynskyi  I'm not so sure and neither should you.
Fresh concept, joining together all here present, is: 
1. All definedTask definitions with empty profiles list.
2. All profiles added by function addProfile() with 3 parameters:
a) profession name
b) profile definition
c) base profile name (optional, if ommited - fresh profile, <b>without any base</b>, added)
3. additional pseudo-task "+" which means add all task from lower defined list (combination made inside function addProfile())
4. In added profile empty level allowed eg. level[i] may be undefined (this issue)

Working <b>testing</b> branch is <a href=https://github.com/WloBeb/NW-Profession-Bot/blob/c1abc1abc425a95ccee0061c8e4e08eaa1d83161/main.js>here</a>. 
Any constructive criticism about conception (not code) welcome.

**Comment by dlebedynskyi** [comment]
@WloBeb should not be any problems to create this. 
1. easy
1. c - just remove look for default of XP. Just remove 

```
719:  if (!base) { base = (professionSet.taskListName === 'Leadership' ? 'XP' : 'default');}
```
1.  remove recursiveList
   In the 

```
for(var i = 0; i<= maxLevel; i++){

```

and check for '+'  ets. 

All other is good to stay as it in. Have looked at your brunch - don't really see how it is easier then working one 
any way 

```
but in javascript === or == for string doesn't work?
```

it does work. http://stackoverflow.com/questions/523643/difference-between-and-in-javascript

You do need to clean up that code a lot. 
Im busy atm. May write this function over the weekend

**Comment by WloBeb** [comment]
@dlebedynskyi My master branch is a little different from master branch of @Phr33d0m.
I still use your old addProfileToDefined() function, but have small changes in ZEX (do you know that there is still <b>very small</b> issue in yours master branch?). My master branch is working, but I have no time to check if changes are correct so I didn't send "Pull request".
When I decided to try to write this idea I just make fork from <b>my</b> master branch. And when I found that it works as expected just push this branch to github.
Perhaps you noticed that I have another one testing branch called "indexedDB" :D. But I have a break in it, because I'm not sure what data we want to store in database (format of data). More about this in @noonereally  <a href=https://github.com/noonereally/NW-Profession-Bot/issues/22>issue.</a> I probably will send today my questions there.

**Comment by dlebedynskyi** [comment]
~When I decided to try to write this idea I just make fork from my master branch. And when I found that it works as expected just push this branch to github.~
you should always fork master. By the time you deside something - you gonna be merge hell. I think you overvalue _your_ master over team master. And yeah your code for addProfile is pretty much same as new one. Just more crap and non js  code styles.  It feel like you never uses history in git, but Im glad you prefer old function lol

Im not here to track every ones private fork. I and most of people contribute to master. Hope you can do the same, otherwise oh well.

**Comment by noonereally** [comment]
Sorry for the delay, but i still plant to merge the "+" and the null completion in 
profiles.
With the profile as second parameter (mandatory) and not last optional.
And the loop inside the function so the profile will be complete after it leaves the function.
(there is a logic in that, for something planned ahead)
