### ISSUE TITLE
indexedDB

### ISSUE THREAD

**Issue by WloBeb** [noonereally/NW-Profession-Bot#22]
@noonereally 
When it comes to IndexedDB, I think we should start by creating a new object, which (at the moment) will replace all GM_ function calls 
Something like this:

<pre>var settingsStorage = {
     init: function () {};
     open: function () {};
     close: function () {};
     load: function () {};
     save: function () {};
};</pre>

I think the biggest problem are GM_listValues() calls....

**Comment by WloBeb** [comment]
@noonereally Can it be something like <a href=https://github.com/WloBeb/NW-Profession-Bot/commit/f3dade53bbd60cc39aa16ca85a434c45ed1e53c4>this</a>
I admit that I'm not familiar with NoSQL database. As well as asynchronous access to database.

BTW. When I browsed it, I wondered whatfor 'charcurrent' variable is stored in database?

**Comment by WloBeb** [comment]
@noonereally  I have some question to <a href=https://github.com/noonereally/NW-Profession-Bot/pull/21#issuecomment-97418723> this</a> note, especialy to part "structure per char, <b>account</b> and global".
1. Do I understand correctly that we need 3 indexedDB ObjectStores - one for global, one for account, and one for character? And it should be only one object in "global" ObjectStore? And only one in "account" ObjectStore <b>for now</b>?
2. What is the difference between global and account data structure? Do you have support for multiple account in plans?
3. As I understand there should be only 1 object in database for every character? 
Object store should be defined this way?

<pre>objectStore = db.createObjectStore("character", { keyPath: "account_character" });</pre>

Stored object should looks like:

<pre>{
    account_character : accountname + "@" + charname;
    nw_charname : charname;
    Leadership : 9;
    Leadership_profile : "AD";
    Leadership_priority : 0;
    // and so on for every profession
    // or even:
    Leadership : {
        slots : 9;
        profile : "AD";
        priority : "0";
    }
    // for every profession
}</pre>

It seems to me that the implementation of indexedDB shouldn't be too difficult, when only we <b>all</b> agree to what objects we want to store.

**Comment by noonereally** [comment]
I'll try to clear few things (at least how I see them),
The main thing that needs testing is the namespace.
Indexeddb has the 'same origin' policy (same way as ajax does) so it should follow the 'namespace' tag the script does (the "@namespace https://greasyfork.org/scripts/7061-neverwinter-gateway-professions-robot/" - btw with RM forking heavily from our builds maybe it will make sense to change it). 
But it can be possible that the nature of how tempermonkey works allows the client (gateway) see the indexeddb, if it so, indexeddb can't be implemented here at all for 'security' reasons and optimizations to gm_save will have to do.

indexeddb ha some similarity to SQL, the most important parts are 'tables' (objectstores) and 'keys'/'indexes' and a value, but in a 'row' we put an object and not a value in our case.
The object that I believe that should be stored are in 3 stores, 
char settings - full object that store all the settings for a single char.
char statistics - all the collected data and changed more frequently.
account settings - the settings of the account.
I've already made the objects some changes ago and they are based on 
defaultAccountSettings , defaultCharSettings , defaultCharStatistics .

Where the key will be @handle,  char name@handle, char name@handle
as they are guarantied to be unique in those stores.

char last visit, char next job time, and sca last visit should move to the char statistic as it is saved every char change anyway.

**Comment by noonereally** [comment]
As i wrote earlier (https://github.com/noonereally/NW-Profession-Bot/pull/21), yes, this will allow multiple account and multiple tabs.

For now i don't see the need for a global one, as the data is very small (some delay settings and the accounts to login if there is auto login enabled)
for now it can remain in gm_save

there is a good info about idb at 
https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB

**Edit**
*_make sure you check those objects (defaultAccountSettings , defaultCharSettings , defaultCharStatistics .) before doing anything, they have all the tasks. They only need small update for recent changes and the key if a key path chosen and not external key  *_

**Comment by noonereally** [comment]
About those objects, their structure  is fixed on purpose at a depth of two. 
for example object.general.parameter
like: accountObject.consolidationSettings.bankName
This was made so it will be possible to have a more or less a single function to be called on settings save.

If I have a seetingsUI array entry
`{ name: 'bankchar', title: 'Character Name of Banker', type: 'text',  pane: 'bank', tooltip: 'Enter name of the character to hold account AD',  scope: 'account', group: "consolidationSettings", paramater: "bankName" }`

`scope: 'account', group: "consolidationSettings", paramater: "bankName"`
will allow to make a function that adds inputs like

`<input type="text" name="settings_accounts..." data-scope="account" data-group="consolidationSettings"...`

And a bind on change that will save it to the object and fire the database transaction. 
for char settings similarly 
`<input type="text" name="seetings__character..." data-scope="cahracter" data-charName="charname will be here" data-group="consolidationSettings"...`

This will also disable the need for the save button, a simple color change on succes for 1-2 seconds to green of the said input for example can mark a successful save (on-complete event of the transaction)
Even if indexeddb will not be possible this should solve the save issue with gm_save freezing everything.

**Comment by RottenMind** [comment]
We borrow -builds, only thing what was usefull for me from your current -build is character name fetch and that feature is really nice and credits are given to you, ;).

Moving fully to Git build is not good idea, because even now I got complaining after updates so it is better for me keep stable version on Greasyfork.

And change that namespace is recommended, because after that each user who is using Git -build understand that Greasyfork has no same build. It moves Github users ask support proper place.

I dont mind to help those who ask help, but scripts features and problems are different.

Multiple accounts per script is nice plan and running script on 1 - 5 TAB´s is possible, but needs Multilogin and so on, so  currently only plan to make script working with Multiaccount is just account switch, but it will be other version for that.

ps. Github is forked from Greasyfork so may I say you "heavily fork from fork", ;).

**Comment by noonereally** [comment]
"And change that namespace is recommended, because after that each user who is using Git -build understand that Greasyfork has no same build. It moves Github users ask support proper place."

It has nothing to do with users, it's limit on the code scope that sets what variables are shared and what not for example, limits the indexeddb access to said namespace (hopefully).

"Moving fully to Git build is not good idea, because even now I got complaining after updates so it is Better for me keep stable version on Greasyfork."
You are the only one updating greesyfork, and you were told before that you change versions to frequently, it has nothing to do with builds. Git doesn't push auto updates.
People complain because your updates delete their custom changes, it has nothing to do with me.
More so, the main difference (the profiles) allows people to add their changes and have them updated, or add a file of their own that will add profiles to any build that we will make. without any change to the code.

"I dont mind to help those who ask help, but scripts features and problems are different." 
I do not believe I ever saw that someone asked you for help on this build, but even if someone did feel free show them how to open issues. 
More so you each time the git builds mentioned you emphasize that there is no one to talk to. And yet people are free to open issues here (or more correctly at the main branch).

"but needs Multilogin and so on"
This is not correct, you have a problem with the namespace, your variables are shared and settings are shared, that's why you need multilogon plugin, this is easy to fix by appending the account.
The proposed changes do not need multilogin nor have those problems.

"Github is forked from Greasyfork so may I say you "heavily fork from fork"" 
Actually Git was/is just an environment to develop and sync better and then push to greesy, to facilitate better communication and code management, it was your and only your choice to fork out. 
of course you are free to do so.

At the end, as I said, it was your choice, and it's a shame as it impacts the progress of the script as a whole.

**Comment by noonereally** [comment]
btw, you shoudn't credit me but @mac-nw for the names.

**Comment by RottenMind** [comment]
What ever, MAC-NW is mentioned like all others and script is still whole.

And it is not shame to anyone that they go with their own path.

About Multilogin.

I am not sure what you are meaning. Did you try open two tabs on browser and login both tab different accounts, script are not installed.

...and do you know why users run account on different browsers and not on same  browser on TAB´s.

...but if there is other solution than Multilogin extension for TAB´s  then it will be really great.

...and there is no problems with settings or variables, problem is with that TAB´s share cookies and Multilogin plugin makes each new TAB on same web -site invidual tampering with cookies.

And again, if you are  can make script running multiple TAB's with different account and no multilogin needed, then it is good to know how it can be done.

So basically I look forward to see that you test login on same web browser two different accounts.... ooops cookiemonster, ;).

...but multiple accounts with account switch will work and Im testing it just now. Just primitive loops make each account invidual adding "acc_nro" on those setting I needed, then make it save "acc_Next_Task", log out and check if all accounts has "acc_Next_Task" etc. 

Very bad coding, but working. Making it work well needs stuff be done what you allready started planing so that is good development.

....but again Git -build is too far away from Greasyfork users now, you better start new fork and get users switch to new. I simply cant force them to this build.

So all is good and Im not sad that you feel sad for me, ;). 

Cheers

BTW, your build is nice and allways when some users cry Greasyfork -build or even if they dont, I gracefully mention that Github has great mod from this script and in it you can get all cool stuff.

**Comment by RottenMind** [comment]
oh, need add, you need Multilogin + TAB Redirect, so Multilogin make TAB REdirect TAB cookies renamed, TAB Redirect must be set to NW site....

After that if you have script what check TAB ID´s and assign acc_nro per TAB ID, you can then run up to 5xTAB, after 5 accounts website (gateway) starts freeze and this happen with script and without it.

Sometimes TAB/account get mixed it (lag and reloads) but I got quite long runs with out problems with that setup, but those cookies are shared via TAB´s so you see 5x samekind cookies with @@@6_, @@@8 etc. when you check cookiemonster nest, ;).

**Comment by noonereally** [comment]
Unfortunately indexedb wont work, it's accessible from the gateway itself and as such will be a clear giveaway for script usage.

**Comment by Phr33d0m** [comment]
@noonereally it's not that they don't know about this already ;-)
